Update Jenkinsfile_boolean

diff --git a/Jenkinsfile_boolean b/Jenkinsfile_boolean
--- a/Jenkinsfile_boolean
+++ b/Jenkinsfile_boolean
@@ -1,30 +1,54 @@
-boolean stageResult = true
+boolean testPassed = true
 
 pipeline {
-    agent any
+	agent any 
+	stages {
+		stage('Build') {
+			steps {
+					echo "Build stage ............"
+					sh 'sleep 5'
+			}	
+		}
+		
+		stage('Test') {
+			steps {
+				script { 
+					try{
+						echo "Running test cases .........."
+						sh 'sleep 5'
+						sh 'exit 1'
+					}catch (Exception e){
+						echo "Test case failed ........"
+						testPassed = false
+					}
+				}	
+			}	
+		}
 
-    stages {
-        stage ('STAGE1') {
-            steps {
-                script {
-                    try{
-                        echo "this is stage1"
-                        sh 'sleep2'
-                        sh 'exit 1'
-                    }catch (Exception e){
-                     stageResult == false
-
-                    }
-                }
-            }
-            stage ('STAGE2') {
-                steps {
-                    scirpt {
-                        if (stageResult == false) 
-                        echo "stage 2 should run"
-                    }
-                }
-            }
-        }
-    }
+		stage('DEPLOY') {
+			steps { 
+				script { 
+					if(testPassed){
+						echo "Deploying to test environment ...."
+						sh 'sleep 5'
+						sh 'exit 1'
+					} else {
+						echo "Skipping deployment ........"
+					}
+				}	
+			}	
+		}
+		
+		stage('MAIL') {
+			steps { 
+				script { 
+					if(!testPassed){
+						echo "Sending mail on test fail"
+					} else { 
+						echo "Sending mail on deplyment success"
+					}
+				}
+			}	
+		}
+	}	
 }
